### ISSUE TITLE
Prueba de issue

### ISSUE THREAD

**Issue by JuanJoseGH06** [biogeografia-201902/unidad-0-asginacion-1-preguntas-investigacion-JuanJoseGH06#1]
Solo una confusión en RStudio, para crear un nuevo proyecto tenia que poner mi cuenta y contraseña de GitHub y yo estaba poniendo la de RStudio, pero al final lo pude hacer

**Comment by geofis** [comment]
¡Genial! Sin embargo, ten en cuenta que el *issue* debes generarlo en la asignación [unidad-0-asignacion-1b-asig-conrstudio-issues](https://github.com/biogeografia-201902/unidad-0-asignacion-1b-asig-conrstudio-issues-JuanJoseGH06). Ve a ese repo y hazlo desde allá.
